version = 1

[[annotations]]
path = [
    ".gas-snapshot",
    ".github/**/",
    ".gitignore",
    ".gitmodules",
    "audit/**/",
    "README.md",
    "flake.lock",
    "flake.nix",
    "foundry.toml",
    "foundry.lock",
    "slither.config.json",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
