version = 1

[[annotations]]
path = [
    ".gas-snapshot",
    ".github/**/",
    ".gitignore",
    "README.md",
    "flake.lock",
    "flake.nix",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
